services:
  spark-master:
    # Dùng bản 3.5.1 - Mặc định đã có Python 3.10
    image: apache/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000
      - SPARK_PYSPARK_PYTHON=python3
    volumes:
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./hive-site.xml:/opt/spark/conf/hive-site.xml
      - /home/kem:/opt/workspace
    networks:
      - bigdata-net

  spark-worker:
    # Dùng bản 3.5.1
    image: apache/spark:3.5.1
    container_name: spark-worker
    hostname: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000
      - SPARK_PYSPARK_PYTHON=python3
    depends_on:
      - spark-master
    volumes:
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./hive-site.xml:/opt/spark/conf/hive-site.xml
      - /home/kem:/opt/workspace
    networks:
      - bigdata-net

networks:
  bigdata-net:
    external: true



